---
title: "final_project_proposal"
author: "Kimia Faroughi, Zakari Billo, Lawrence Zicari, Sukhman Parhar"
date: "2025-11-06"
output: github_document
---

## Group Members

* Kimia Faroughi (UNI: ksf2129)
* Lawrence Zicari (UNI: lz3015)
* Sukhman Parhar (UNI: sp4436)
* Zakari Billo (UNI: zlb2008)


## Tentative Project Title

Beyond the Spread: Analyzing the Demographics of a Gambling Epidemic


## Motivation for Project

Sports gambling has been on the rise in recent years. Whether you are watching sports, TV with ads, social media content, or even just taking the subway, you are being exposed in one way or another to sports betting advertisements. With little regulation and large-scale scandals surrounding sports betting in recent months, an analysis of the key demographics of who partakes the most in sports gambling will be critical in understanding how to create and implement programs to effectively reduce the burden of gambling addictions that are surely to be on the rise in the upcoming years. Assessing education & income status, age, and proximity to a major sports team are among the demographic factors we want to investigate. Additionally, we may be able to project the market sizes of sports gambling in states that have yet to legalize it, such as California. 


## Intended Final Products

* Website detailing the market size of sports gambling by state 
* Model predicting gambling revenue based on demographics (education & income status, age, and proximity to a major      sports team)


## Anticipated Data Sources

* [US sports betting revenue](https://rg.org/statistics/us)
* NHANES or Census for demographic data


## Planned Analyses/Visualizations/Coding Challenges

* Exploratory analyses of demographic data
* Mapping gambling revenue across states, across time (pre and post-legality)
* Challenges:
    * Getting reliable betting data (often is proprietary for obvious reasons)
    * Making causal conclusions 


## Planned Timeline

* Scrape data from the betting revenue website
* Compile and clean relevant NHANES demographic data
* Exploratory analyses of relevant variables
* Create a model that predicts gambling revenue across states, based on demographics