---
title: "exploring_demographic_data"
output: github_document
---

```{r packages}
library(tidyverse)
library(patchwork)

knitr::opts_chunk$set(
fig.width = 6,
fig.asp = .6,
out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
ggplot2.continuous.colour = "viridis",
ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Import data

```{r, message = FALSE}
model_clean_2024 = read_csv("data/model_clean_2024.csv")
```

## Explore

Plot of Total Population in 2024 by State

```{r}
population_plot = 
  model_clean_2024 |> 
    filter(State != "Washington D.C.") |> #drop DC bc all demographic data is NA
    mutate(
      State = as.factor(State),
      State = fct_reorder(State, total_pop, .desc = TRUE)
    ) |> 
    ggplot(aes(x = State, y = total_pop)) +
    geom_col(aes(fill = State)) +
    theme(
      axis.text.x = element_text(angle = 90, hjust = 1, vjust = 1),
      legend.position = "none") +
    labs(
        y = "Total Population",
        title = "Total Population by State in 2024"
      )
```

Plot of Gambling Revenue in 2024 by State

```{r}
revenue_plot = 
  model_clean_2024 |> 
    filter(State != "Washington D.C.") |> #drop DC bc all demographic data is NA
    mutate(
      State = as.factor(State),
      State = fct_reorder(State, total_pop, .desc = TRUE)
    ) |> 
    ggplot(aes(x = State, y = Revenue)) +
    geom_col(aes(fill = State)) +
    theme(
      axis.text.x = element_text(angle = 90, hjust = 1, vjust = 1),
      legend.position = "none") +
    labs(
        x = "State (in order of largest to smallest total population)",
        y = "Revenue",
        title = "Gambling Revenue by State in 2024"
      )
```

Patchwork Plot of Total Population and Gambling Revenue in 2024 by State

```{r, fig.width = 10}
combined_revenue_population = (population_plot + revenue_plot)

combined_revenue_population
```

Racial Makeup of States in 2024

```{r}
model_clean_2024 |> 
  filter(State != "Washington D.C.") |> #drop DC bc all demographic data is NA
  select(State, Revenue, pct_white, pct_black, pct_asian, pct_hispanic) |> 
  pivot_longer(
    cols = pct_white:pct_hispanic,
    names_to = "race",
    values_to = "percentage"
  ) |> 
  mutate(
      State = as.factor(State),
      State = fct_reorder(State, Revenue, .desc = TRUE),
      race = factor(race,
                  levels = c("pct_white", "pct_black", "pct_asian", "pct_hispanic"),
                  labels = c("% White", "% Black", "% Asian", "% Hispanic"))
  ) |> 
  ggplot(aes(x = State, y = percentage, color = race, group = race)) +
  geom_point() +
  geom_line() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 1)) +
    labs(
        x = "State (in order of largest to smallest gambling revenue)",
        y = "Percentage of Population",
        title = "Racial Makeup by State in 2024",
        fill = "Race"
    ) 
```

% Poverty and Unemployment Rate by State in 2024

```{r}
model_clean_2024 |> 
  filter(State != "Washington D.C.") |> #drop DC bc all demographic data is NA
  select(State, Revenue, unemployment_rate, pct_poverty) |> 
  pivot_longer(
    cols = c("pct_poverty", "unemployment_rate"),
    names_to = "measure",
    values_to = "percentage"
  ) |> 
  mutate(
      State = as.factor(State),
      State = fct_reorder(State, Revenue, .desc = TRUE),
      measure = factor(measure,
                  levels = c("pct_poverty", "unemployment_rate"),
                  labels = c("% in Poverty", "% Unemployed"))
  ) |> 
  ggplot(aes(x = State, y = percentage, color = measure, group = measure)) +
  geom_point() +
  geom_line() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 1)) +
    labs(
        x = "State (in order of largest to smallest gambling revenue)",
        y = "Percentage of Population",
        title = "% Poverty and Unemployment Rate by State in 2024",
        fill = "Measure"
    ) 
```